server:
  port : 8085

cloud:
  aws:
    region:
      static: us-east-1
      use-default-aws-region-chain: true
      auto: false
    stack:
      auto: false
    credentials:
      access-key: test
      secret-key: test
    queue:
      endpoint: http://localhost:4566
      tax-payments: tax-payments